import { FileText, ShieldCheck } from "lucide-react";

const delivery = [
  ["Phase 1", "Typed application shell, API foundation, configuration, and deployment scaffolding."],
  ["Phase 2", "Secure temporary image upload, real pixel analysis, histograms, and no-reference noise estimates."],
  ["Phase 3", "Validated denoising, enhancement, compression, previews, and full-reference metrics."],
  ["Phase 4", "Persistent experiments, reproducible ranking, history, duplicate protection, and exports."],
  ["Phase 5", "Random Forest recommendations trained from saved outcomes with explanations and limitations."],
  ["Phase 6", "Mathematical reference, accessibility/responsive/security review, and final operational documentation."],
];

export function AboutPage() {
  return <div className="space-y-8 pb-10"><header className="rounded-3xl border border-line bg-surface p-6 shadow-card sm:p-10"><p className="eyebrow">Project reference</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-ink sm:text-4xl">MathVision AI</h1><p className="mt-4 max-w-3xl text-base leading-8 text-ink-muted">A measurable image-analysis workspace that connects mathematical transforms, image-processing experiments, and explainable model recommendations.</p><div className="mt-6 flex flex-wrap gap-3"><span className="status-badge status-badge-blue">Phase 6 complete</span><span className="text-sm text-ink-muted">See the repository README and deployment guide for operations.</span></div></header><section aria-labelledby="delivery-heading"><div className="mb-5 flex items-center gap-3"><FileText className="text-cyan" size={22} /><div><p className="eyebrow">Delivery history</p><h2 id="delivery-heading" className="mt-2 text-2xl font-semibold text-ink">What the platform contains.</h2></div></div><div className="space-y-3">{delivery.map(([phase, description]) => <article className="rounded-2xl border border-line bg-surface p-5 shadow-card sm:flex sm:items-start sm:gap-5" key={phase}><span className="status-badge status-badge-violet shrink-0">{phase}</span><p className="mt-3 text-sm leading-6 text-ink-muted sm:mt-0">{description}</p></article>)}</div></section><section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-line bg-surface p-6 shadow-card"><h2 className="text-xl font-semibold text-ink">Operational boundaries</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-ink-muted"><li>Uploaded images and generated outputs are temporary and expire according to retention settings.</li><li>Recommendations learn from this project’s saved experiment outcomes; they are not benchmark-grounded clinical or production decisions.</li><li>PSNR and SSIM require a reference image and should be interpreted alongside visual inspection.</li></ul></div><div className="rounded-2xl border border-green-200 bg-green-50 p-6 dark:border-green-900 dark:bg-green-950/20"><div className="flex items-center gap-2 text-green-700 dark:text-green-300"><ShieldCheck size={19} /><h2 className="text-xl font-semibold">Engineering commitments</h2></div><ul className="mt-4 space-y-3 text-sm leading-6 text-green-900 dark:text-green-200"><li>Typed API boundaries with Pydantic and Zod validation.</li><li>Real image-derived values instead of fabricated metrics.</li><li>Structured errors, bounded parameters, migrations, tests, and reproducible builds.</li></ul></div></section></div>;
}
