import { ArrowRight, BrainCircuit, ChartNoAxesCombined, CircuitBoard, FlaskConical, Gauge, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";

import { StatusBadge } from "../components/common/StatusBadge";

const valueCards = [
  { icon: ChartNoAxesCombined, title: "Mathematical image analysis", body: "A foundation for measurable, reproducible image experiments." },
  { icon: BrainCircuit, title: "Explainable intelligence", body: "Recommendation logic will remain traceable as the platform grows." },
  { icon: Gauge, title: "Objective comparison", body: "Quality, speed, and compression will be compared using explicit metrics." },
  { icon: ShieldCheck, title: "Reliable foundations", body: "Typed boundaries, validation, tests, and safe defaults from the start." },
];

export function HomePage() {
  return <div className="space-y-12 pb-10">
    <section className="hero-grid overflow-hidden rounded-3xl border border-line bg-surface shadow-card"><div className="relative z-10 p-6 sm:p-10 lg:p-14"><StatusBadge tone="violet">Phase 6 · Complete platform</StatusBadge><h1 className="mt-6 max-w-3xl text-4xl font-semibold tracking-tight text-ink sm:text-5xl">Image intelligence grounded in mathematics.</h1><p className="mt-5 max-w-2xl text-base leading-8 text-ink-muted sm:text-lg">MathVision AI is a scientific platform for understanding, improving, and explaining image-processing decisions with real pixels, reproducible experiments, and transparent model limits.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="primary-button" to="/workspace"><Sparkles size={18} />Start image analysis<ArrowRight size={17} /></Link><Link className="secondary-button" to="/mathematics"><BookOpenIcon />Explore the mathematics</Link></div><p className="mt-4 text-xs text-ink-muted">Upload data remains temporary; experiment metadata and metric snapshots are persisted.</p></div><div className="pipeline-panel" aria-label="Scientific image processing pipeline"><div className="mb-6 flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-[0.18em] text-ink-muted">Scientific workflow</span><CircuitBoard className="text-cyan" size={20} /></div><div className="space-y-3">{["Upload", "Analyze", "Process", "Compare", "Explain"].map((step, index) => <div key={step} className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full border border-cyan/30 bg-cyan/10 text-xs font-semibold text-cyan">0{index + 1}</span><span className="text-sm font-medium text-ink">{step}</span>{index < 4 && <span className="ml-auto h-5 border-l border-dashed border-line" aria-hidden="true" />}</div>)}</div></div></section>
    <section aria-labelledby="value-heading"><div className="section-heading"><div><p className="eyebrow">Why MathVision AI</p><h2 id="value-heading">A clear path from pixels to evidence.</h2></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{valueCards.map(({ icon: Icon, title, body }) => <article className="foundation-card" key={title}><div className="icon-tile"><Icon size={20} /></div><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr]" aria-labelledby="how-heading"><div className="rounded-2xl border border-line bg-surface p-6 sm:p-8"><p className="eyebrow">How it works</p><h2 id="how-heading" className="mt-2">Built incrementally, measured honestly.</h2><div className="mt-6 grid gap-5 sm:grid-cols-2">{["Define the image question", "Extract trustworthy evidence", "Apply a verified method", "Compare measurable outcomes", "Explain the trade-offs"].map((step, index) => <div className="flex gap-3" key={step}><span className="font-mono text-sm font-semibold text-brand">0{index + 1}</span><p className="text-sm leading-6 text-ink-muted">{step}</p></div>)}</div></div><div className="rounded-2xl border border-violet/20 bg-violet/5 p-6 sm:p-8"><p className="eyebrow text-violet">Technology direction</p><h2 className="mt-2">From numerical foundations to explainable AI.</h2><div className="mt-6 space-y-4 text-sm text-ink-muted"><p><strong className="text-ink">Mathematics:</strong> transforms, statistics, and objective quality measures.</p><p><strong className="text-ink">Image processing:</strong> safe, reproducible operations on real image data.</p><p><strong className="text-ink">Machine learning:</strong> transparent recommendations with honest fallbacks.</p><p><strong className="text-ink">Engineering:</strong> typed APIs, tests, migrations, security headers, and reproducible deployment.</p></div></div></section>
  </div>;
}

function BookOpenIcon() { return <FlaskConical size={18} />; }
