import { BookOpenText, Calculator, Sigma } from "lucide-react";
import { BlockMath, InlineMath } from "react-katex";
import "katex/dist/katex.min.css";

type Method = { name: string; purpose: string; formula: string; symbols: string; example: string };

const latex = (value: string): string => value.replaceAll("§", String.fromCharCode(92));

const transforms: Method[] = [
  { name: "Discrete Wavelet Transform (DWT)", purpose: "Separates an image into approximation and detail sub-bands at multiple scales.", formula: latex("W_{§psi}(a,b)=§frac{1}{§sqrt{|a|}}§sum_{n}x[n]§,§psi^*§!§left(§frac{n-b}{a}§right)"), symbols: "x is the signal, psi is the mother wavelet, a controls scale, and b controls translation.", example: "A Haar level decomposes a 2x2 patch into one average coefficient and horizontal, vertical, and diagonal detail coefficients." },
  { name: "Discrete Cosine Transform (DCT)", purpose: "Concentrates smooth image energy in low-frequency coefficients, which supports compression.", formula: latex("C(u,v)=§alpha(u)§alpha(v)§sum_{x=0}^{N-1}§sum_{y=0}^{N-1}f(x,y)§cos§frac{(2x+1)u§pi}{2N}§cos§frac{(2y+1)v§pi}{2N}"), symbols: "f is an N x N block, (u,v) is a frequency coordinate, and alpha normalizes the coefficients.", example: "Keeping the low-frequency corner of an 8x8 block usually preserves broad shapes while discarding fine variation." },
  { name: "Fast Fourier Transform (FFT)", purpose: "Represents spatial variation as complex frequency components and enables spectral inspection.", formula: latex("X[k]=§sum_{n=0}^{N-1}x[n]e^{-2§pi i kn/N}"), symbols: "x[n] is the sampled signal, X[k] is its frequency coefficient, and i squared equals -1.", example: "A periodic stripe pattern produces concentrated peaks at the stripe frequency and its conjugate." },
  { name: "Singular Value Decomposition (SVD)", purpose: "Approximates an image matrix with a controlled number of dominant rank-one components.", formula: latex("A=U§Sigma V^T§approx U_r§Sigma_rV_r^T"), symbols: "U and V are orthogonal bases, Sigma contains singular values, and r is the retained rank.", example: "Retaining r singular values creates a rank-r approximation; larger r generally preserves more detail and costs more storage." },
];

const metrics: Method[] = [
  { name: "Mean Squared Error (MSE)", purpose: "Measures the average squared pixel difference between a reference and a processed image.", formula: latex("§operatorname{MSE}=§frac{1}{mn}§sum_{i=1}^{m}§sum_{j=1}^{n}(I_{ij}-K_{ij})^2"), symbols: "I is the reference image, K is the result, and m,n are image dimensions.", example: "For reference [0,100] and result [10,90], MSE=(10 squared + 10 squared)/2=100." },
  { name: "Peak Signal-to-Noise Ratio (PSNR)", purpose: "Expresses reconstruction fidelity on a logarithmic decibel scale when a reference exists.", formula: latex("§operatorname{PSNR}=10§log_{10}§left(§frac{MAX_I^2}{§operatorname{MSE}}§right)"), symbols: "MAX_I is the maximum representable intensity; for 8-bit images it is 255.", example: "With 8-bit pixels and MSE=100, PSNR is approximately 28.13 dB. Perfect equality is represented separately because MSE=0." },
  { name: "Structural Similarity (SSIM)", purpose: "Compares local luminance, contrast, and structure rather than only pixel-wise error.", formula: latex("§operatorname{SSIM}(x,y)=§frac{(2§mu_x§mu_y+c_1)(2§sigma_{xy}+c_2)}{(§mu_x^2+§mu_y^2+c_1)(§sigma_x^2+§sigma_y^2+c_2)}"), symbols: "mu values are local means, sigma values are variances/covariance, and c1,c2 stabilize low-contrast regions.", example: "SSIM is interpreted together with its local-window and reference-image limitations." },
  { name: "Entropy", purpose: "Measures uncertainty or information content in the empirical intensity distribution.", formula: latex("H(X)=-§sum_{k}p_k§log_2(p_k)"), symbols: "p_k is the observed probability of intensity bin k; zero-probability bins contribute zero by convention.", example: "A distribution with two equally likely intensity values has entropy equal to 1 bit per sample." },
];

function MethodCard({ method }: { method: Method }) {
  return <article className="rounded-2xl border border-line bg-surface p-5 shadow-card sm:p-7"><h3 className="text-xl font-semibold text-ink">{method.name}</h3><p className="mt-3 text-sm leading-6 text-ink-muted">{method.purpose}</p><div className="math-formula mt-5 overflow-x-auto rounded-xl border border-cyan/20 bg-cyan/5 p-4 text-ink"><BlockMath math={method.formula} /></div><dl className="mt-5 space-y-3 text-sm leading-6"><div><dt className="font-semibold text-ink">Symbols</dt><dd className="text-ink-muted">{method.symbols}</dd></div><div><dt className="font-semibold text-ink">Small example</dt><dd className="text-ink-muted">{method.example}</dd></div></dl></article>;
}

export function MathematicsPage() {
  return <div className="space-y-10 pb-10">
    <header className="rounded-3xl border border-line bg-surface p-6 shadow-card sm:p-10"><div className="flex items-start gap-4"><div className="icon-tile shrink-0"><BookOpenText size={22} /></div><div><p className="eyebrow">Phase 6 · Mathematical methods</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-ink sm:text-4xl">From pixels to measurable evidence.</h1><p className="mt-4 max-w-3xl text-base leading-8 text-ink-muted">This reference connects the implemented image-processing pipeline to the mathematics behind it. Equations describe the method; the API values are computed from uploaded pixels and saved processing outputs.</p></div></div><div className="mt-7 rounded-2xl border border-violet/20 bg-violet/5 p-4 text-sm leading-6 text-ink-muted"><strong className="text-ink">Interpretation rule:</strong> no single metric is a complete definition of visual quality. Compare PSNR and SSIM with the image, algorithm, execution time, and known limitations.</div></header>
    <section aria-labelledby="pipeline-equation-heading" className="rounded-2xl border border-line bg-surface p-5 shadow-card sm:p-7"><div className="flex items-center gap-3"><Sigma className="text-violet" size={22} /><div><p className="eyebrow text-violet">The project objective</p><h2 id="pipeline-equation-heading" className="mt-2 text-2xl font-semibold text-ink">Choose a useful trade-off, not just a large number.</h2></div></div><div className="math-formula mt-6 overflow-x-auto rounded-xl border border-violet/20 bg-violet/5 p-4 text-ink"><BlockMath math={latex("§operatorname{Score}=§alpha§,§operatorname{PSNR}+§beta§,§operatorname{SSIM}-§gamma§,§operatorname{Time}-§delta§,§operatorname{Size}")} /></div><p className="mt-4 text-sm leading-6 text-ink-muted">The comparison API uses a reproducible policy based on SSIM, normalized PSNR, and execution speed. The displayed ranking policy is the authoritative implementation.</p></section>
    <section aria-labelledby="transforms-heading"><div className="mb-5 flex items-end gap-3"><Calculator className="text-cyan" size={22} /><div><p className="eyebrow">Transforms</p><h2 id="transforms-heading" className="mt-2 text-2xl font-semibold text-ink">Represent the image in a useful basis.</h2></div></div><div className="grid gap-5 lg:grid-cols-2">{transforms.map((method) => <MethodCard key={method.name} method={method} />)}</div></section>
    <section aria-labelledby="metrics-heading"><div className="mb-5"><p className="eyebrow">Statistics and quality</p><h2 id="metrics-heading" className="mt-2 text-2xl font-semibold text-ink">Measure what changed.</h2></div><div className="grid gap-5 lg:grid-cols-2">{metrics.map((method) => <MethodCard key={method.name} method={method} />)}</div></section>
    <section aria-labelledby="notation-heading" className="rounded-2xl border border-line bg-surface p-5 shadow-card sm:p-7"><h2 id="notation-heading" className="text-xl font-semibold text-ink">Notation used in the application</h2><div className="mt-5 grid gap-4 text-sm leading-6 text-ink-muted sm:grid-cols-3"><p><InlineMath math="I" /> reference image</p><p><InlineMath math="K" /> processed image</p><p><InlineMath math="MAX_I" /> maximum intensity</p><p><InlineMath math={latex("§mu")} /> local mean</p><p><InlineMath math={latex("§sigma")} /> standard deviation</p><p><InlineMath math={latex("p_k")} /> empirical probability</p></div></section>
  </div>;
}
