import { ArrowLeft, Download, LoaderCircle, Sigma, Sparkles } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";

import { mathematicalAnalysisExportUrl, runMathematicalAnalysis } from "../services/api";
import type { MathematicalAnalysisResponse, MathematicalSection } from "../schemas/api";
import { FormulaExplanation, Heatmap, KeyValueTable, LineChart, MatrixPreview, Metric, MetricGrid, numberArray, numberMatrix, numberValue, SectionCard, stringValue, value } from "../features/mathematical-analysis/components";

type Tab = { id: string; label: string };
const tabs: Tab[] = [
  { id: "overview", label: "Overview" }, { id: "matrix", label: "Matrix Representation" }, { id: "statistics", label: "Descriptive Statistics" }, { id: "probability", label: "Probability Distribution" }, { id: "histograms", label: "Histograms" }, { id: "gradients", label: "Gradients and Edges" }, { id: "frequency", label: "Frequency Analysis" }, { id: "wavelets", label: "Wavelet Analysis" }, { id: "svd", label: "Linear Algebra and SVD" }, { id: "texture", label: "Texture Analysis" }, { id: "noise", label: "Noise Analysis" }, { id: "local", label: "Local Mathematical Maps" }, { id: "compression", label: "Compression Potential" }, { id: "report", label: "Mathematical Report" },
];

export function MathematicalAnalysisPage() {
  const { imageId } = useParams<{ imageId: string }>();
  const [analysis, setAnalysis] = useState<MathematicalAnalysisResponse | null>(null);
  const [activeTab, setActiveTab] = useState("overview");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [gridSize, setGridSize] = useState<4 | 8 | 16>(4);

  const run = useCallback(async () => { if (!imageId) return; setLoading(true); setError(null); try { setAnalysis(await runMathematicalAnalysis(imageId, gridSize)); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "The mathematical analysis could not be completed."); } finally { setLoading(false); } }, [gridSize, imageId]);
  useEffect(() => { void run(); }, [run]);

  const section = (key: string): MathematicalSection => { if (!analysis) return {}; const map: Record<string, MathematicalSection> = { overview: analysis.overview, matrix: analysis.matrix, statistics: analysis.statistics, probability: analysis.probability, histograms: analysis.histograms, gradients: analysis.gradients, frequency: analysis.frequency, wavelets: analysis.wavelets, svd: analysis.svd, texture: analysis.texture, noise: analysis.noise, local: analysis.local_maps, compression: analysis.compression, report: analysis.report }; return map[key] ?? {}; };

  return <div className="space-y-7"><header className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><Link to="/workspace" className="inline-flex items-center gap-2 text-sm font-semibold text-cyan hover:underline"><ArrowLeft size={16} />Back to workspace</Link><p className="eyebrow mt-6 text-cyan">Dedicated mathematical workspace</p><h1 className="mt-2 flex items-center gap-3 text-3xl font-semibold tracking-tight text-ink sm:text-4xl"><Sigma className="text-cyan" />Advanced Mathematical Analysis</h1><p className="mt-3 max-w-3xl leading-7 text-ink-muted">Study the uploaded image as a matrix, tensor, discrete signal, probability distribution, and multiscale mathematical object. Every value below is computed from the real uploaded pixels.</p></div><div className="flex flex-wrap items-end gap-2">{analysis && <><label className="text-xs font-semibold text-ink-muted">Local grid<select className="field-input mt-1" value={gridSize} onChange={(event) => setGridSize(Number(event.target.value) as 4 | 8 | 16)}><option value={4}>4 × 4</option><option value={8}>8 × 8</option><option value={16}>16 × 16</option></select></label><a className="secondary-button" href={mathematicalAnalysisExportUrl(analysis.id, "json")} download><Download size={16} />JSON report</a><a className="secondary-button" href={mathematicalAnalysisExportUrl(analysis.id, "csv")} download><Download size={16} />CSV report</a></>}</div></header>
    {loading && <div className="rounded-2xl border border-cyan/20 bg-cyan/5 p-6" role="status"><div className="flex items-center gap-3 text-cyan"><LoaderCircle className="animate-spin" size={22} /><span className="font-semibold">Running advanced mathematical analysis...</span></div><p className="mt-3 text-sm leading-6 text-ink-muted">Computing statistics, spectra, wavelets, SVD, texture, local maps, and the structured report. Expensive operations are bounded and reused.</p></div>}
    {error && <div className="error-panel" role="alert"><p className="font-semibold">Analysis failed</p><p className="mt-1 text-sm">{error}</p><button type="button" className="secondary-button mt-4" onClick={() => void run()}>Try again</button></div>}
    {analysis && <><div className="rounded-2xl border border-cyan/20 bg-cyan/5 p-4"><div className="flex gap-3"><Sparkles className="mt-0.5 shrink-0 text-cyan" size={20} /><div><p className="font-semibold text-ink">Analysis complete in {analysis.duration_ms.toFixed(0)} ms</p><p className="mt-1 text-xs leading-5 text-ink-muted">Version {analysis.analysis_version}. Expensive previews are explicitly downsampled in the returned metadata where applicable; scalar metrics use the uploaded representation.</p></div></div></div><div className="grid gap-2 overflow-x-auto pb-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{tabs.map((tab) => <button type="button" key={tab.id} className={`min-w-[190px] rounded-xl border px-4 py-3 text-left text-sm font-semibold transition ${activeTab === tab.id ? "border-cyan bg-cyan text-white" : "border-line bg-surface text-ink-muted hover:border-cyan/50 hover:text-ink"}`} onClick={() => setActiveTab(tab.id)} aria-selected={activeTab === tab.id}>{tab.label}</button>)}</div><TabContent activeTab={activeTab} analysis={analysis} section={section(activeTab)} /></>}
  </div>;
}

function TabContent({ activeTab, analysis, section }: { activeTab: string; analysis: MathematicalAnalysisResponse; section: MathematicalSection }) {
  if (activeTab === "overview") return <OverviewTab analysis={analysis} section={section} />;
  if (activeTab === "matrix") return <MatrixTab section={section} />;
  if (activeTab === "statistics") return <StatisticsTab section={section} />;
  if (activeTab === "probability") return <ProbabilityTab section={section} />;
  if (activeTab === "histograms") return <HistogramTab section={section} />;
  if (activeTab === "gradients") return <GradientTab section={section} />;
  if (activeTab === "frequency") return <FrequencyTab section={section} />;
  if (activeTab === "wavelets") return <WaveletTab section={section} />;
  if (activeTab === "svd") return <SvdTab section={section} />;
  if (activeTab === "texture") return <TextureTab section={section} />;
  if (activeTab === "noise") return <NoiseTab section={section} />;
  if (activeTab === "local") return <LocalTab section={section} />;
  if (activeTab === "compression") return <CompressionTab section={section} />;
  return <ReportTab analysis={analysis} section={section} />;
}

function OverviewTab({ analysis, section }: { analysis: MathematicalAnalysisResponse; section: MathematicalSection }) {
  const source = analysis.source; const items = [{ label: "Brightness", value: value(section, "brightness"), interpretation: String(value(section, "exposure_interpretation") ?? "") }, { label: "Contrast", value: value(section, "contrast") }, { label: "Entropy", value: value(section, "entropy"), interpretation: "Entropy is a diversity measure, not an automatic quality score." }, { label: "Sharpness", value: value(section, "sharpness") }, { label: "Noise estimate", value: value(section, "noise_estimate") }, { label: "Compression", value: value(section, "compression_potential") }];
  return <div className="space-y-6"><SectionCard title="Image mathematical profile" eyebrow="Overview"><MetricGrid items={[{ label: "Shape", value: JSON.stringify(source.shape) }, { label: "Data type", value: source.dtype }, { label: "Channels", value: source.channels }, { label: "Duration", value: analysis.duration_ms, unit: "ms" }]} /><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <Metric key={item.label} label={item.label} item={item.value} interpretation={item.interpretation} />)}</div><FormulaExplanation formula="I ∈ R^{m×n}  or  I ∈ R^{m×n×3}" interpretation={value(section, "interpretation")} limitations="Overview labels summarize detailed measurements; use the dedicated tabs for definitions and ranges." /></SectionCard><SectionCard title="Analysis contract" eyebrow="How to read the results"><p className="leading-7 text-ink-muted">This workspace reports empirical measurements from the uploaded image. It does not invent a reference image, a trained diagnosis, or a guaranteed compression ratio. Each panel includes the method and limitations relevant to the metric.</p></SectionCard></div>;
}

function MatrixTab({ section }: { section: MathematicalSection }) { const [sampleSize, setSampleSize] = useState(10); const matrix = numberMatrix(value(section, "values")); return <SectionCard title="Matrix and tensor representation" eyebrow="I as data"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Representation" item={value(section, "representation")} /><Metric label="Dimensions" item={`${value(section, "rows")} × ${value(section, "columns")}`} /><Metric label="Scalar values" item={value(section, "scalar_value_count")} /><Metric label="Memory" item={value(section, "memory_bytes")} unit="bytes" /><Metric label="Data type" item={value(section, "data_type")} /><Metric label="Bit depth" item={value(section, "bit_depth")} unit="bits" /><Metric label="Domain" item={JSON.stringify(value(section, "value_domain"))} /><Metric label="Coordinates" item={value(section, "coordinate_convention")} /></div><div className="mt-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-ink">Pixel-region inspector</p><p className="mt-1 text-xs text-ink-muted">Inspect the real decoded sample at the selected top-left region size.</p></div><label className="text-xs font-semibold text-ink-muted">Sample size<select className="field-input mt-1" value={sampleSize} onChange={(event) => setSampleSize(Number(event.target.value))}><option value={3}>3 × 3</option><option value={5}>5 × 5</option><option value={10}>10 × 10</option></select></label></div><div className="mt-4"><MatrixPreview values={matrix.slice(0, sampleSize).map((row) => row.slice(0, sampleSize))} label={`${sampleSize} × ${sampleSize} sample from coordinates ${JSON.stringify(value(section, "origin"))}`} /></div><p className="mt-3 text-xs text-ink-muted">Coordinates use zero-based [row, column, channel] indexing. The backend response intentionally caps the inspectable sample at 10 × 10 to keep the API safe.</p><FormulaExplanation formula="I ∈ R^{m×n} \quad\text{or}\quad I ∈ R^{m×n×3}" symbols={{ m: "rows", n: "columns", 3: "RGB channels" }} method="The decoded image array is copied from the validated temporary upload; no fabricated matrix values are used." limitations={value(section, "limitations")} /></SectionCard>; }

function StatisticsTab({ section }: { section: MathematicalSection }) { const channels = value(section, "channels"); return <SectionCard title="Descriptive statistics" eyebrow="Moments and quantiles"><p className="mb-5 text-sm leading-6 text-ink-muted">Global statistics and channel statistics use all scalar pixels of the uploaded representation. Select a channel in the table to inspect the same definitions.</p><KeyValueTable values={channels} /><FormulaExplanation formula={stringValue(section, "formulae") ?? "μ = (1/N) Σᵢ xᵢ"} symbols={value(section, "symbols")} method={value(section, "method")} limitations={value(section, "limitations")} /></SectionCard>; }

function ProbabilityTab({ section }: { section: MathematicalSection }) { const gray = value(section, "grayscale") as MathematicalSection | undefined; return <SectionCard title="Empirical probability distribution" eyebrow="Pixel intensity as a random variable"><MetricGrid items={[{ label: "Dark probability", value: numberValue(gray ?? {}, "dark_probability") }, { label: "Midtone probability", value: numberValue(gray ?? {}, "midtone_probability") }, { label: "Bright probability", value: numberValue(gray ?? {}, "bright_probability") }, { label: "Black clipping", value: numberValue(gray ?? {}, "black_clipping_probability") }, { label: "White clipping", value: numberValue(gray ?? {}, "white_clipping_probability") }]} /><div className="mt-6 grid gap-4 lg:grid-cols-2"><LineChart values={numberArray(value(gray ?? {}, "pmf"))} label="Probability mass function pₖ" /><LineChart values={numberArray(value(gray ?? {}, "cdf"))} label="Cumulative distribution F(k)" color="#7C3AED" /></div><FormulaExplanation formula={stringValue(section, "formulae") ?? "p_k = P(X=k) = count(X=k)/N"} symbols={value(section, "symbols")} method={value(section, "interpretation")} limitations={value(section, "limitations")} /></SectionCard>; }

function HistogramTab({ section }: { section: MathematicalSection }) { const channels = value(section, "channels"); return <SectionCard title="Histogram explorer" eyebrow="Counts, normalization, and clipping"><div className="grid gap-4 lg:grid-cols-2">{channels && typeof channels === "object" && !Array.isArray(channels) ? Object.entries(channels).map(([name, item]) => { const data = item as MathematicalSection; return <div key={name}><p className="mb-2 text-sm font-semibold text-ink">{name}</p><LineChart values={numberArray(value(data, "counts"))} label={`${name} count histogram`} /><div className="mt-3 grid grid-cols-2 gap-3"><Metric label="Mean" item={value(data, "mean")} /><Metric label="Median" item={value(data, "median")} /><Metric label="Black clipping" item={value(data, "black_clipping_ratio")} /><Metric label="White clipping" item={value(data, "white_clipping_ratio")} /></div></div>; }) : null}</div><FormulaExplanation interpretation={value(section, "interpretation")} limitations={value(section, "limitations")} /></SectionCard>; }

function GradientTab({ section }: { section: MathematicalSection }) { const maps = value(section, "maps"); return <SectionCard title="Gradients, edges, and sharpness" eyebrow="Discrete derivatives"><MetricGrid items={[{ label: "Mean gradient", value: value(section, "mean_gradient_strength") }, { label: "Max gradient", value: value(section, "maximum_gradient_strength") }, { label: "Sobel edge density", value: value(section, "edge_density") }, { label: "Canny density", value: value(section, "canny_edge_density") }, { label: "Laplacian variance", value: value(section, "variance_of_laplacian") }, { label: "Tenengrad", value: value(section, "tenengrad") }]} /><div className="mt-6 grid gap-4 md:grid-cols-2">{maps && typeof maps === "object" && !Array.isArray(maps) ? Object.entries(maps).map(([name, item]) => <Heatmap key={name} values={numberMatrix(item)} label={name.replaceAll("_", " ")} />) : null}</div><FormulaExplanation formula={stringValue(section, "formulae") ?? "‖∇I‖ = √((∂ₓI)² + (∂ᵧI)²)"} method={value(section, "method")} limitations={value(section, "limitations")} /></SectionCard>; }

function FrequencyTab({ section }: { section: MathematicalSection }) { const maps = value(section, "maps"); return <SectionCard title="Fourier frequency analysis" eyebrow="2D discrete signal"><MetricGrid items={[{ label: "Low-frequency energy", value: value(section, "low_frequency_energy_ratio") }, { label: "Mid-frequency energy", value: value(section, "mid_frequency_energy_ratio") }, { label: "High-frequency energy", value: value(section, "high_frequency_energy_ratio") }, { label: "Horizontal periodicity", value: value(section, "horizontal_periodicity_score") }, { label: "Vertical periodicity", value: value(section, "vertical_periodicity_score") }, { label: "Dominant frequency", value: JSON.stringify(value(section, "dominant_frequency")) }]} /><div className="mt-5"><LineChart values={numberArray(value(section, "radial_frequency_profile"))} label="Radial frequency profile" color="#7C3AED" /></div><div className="mt-5 grid gap-4 md:grid-cols-3">{maps && typeof maps === "object" && !Array.isArray(maps) ? Object.entries(maps).map(([name, item]) => <Heatmap key={name} values={numberMatrix(item)} label={name.replaceAll("_", " ")} />) : null}</div><FormulaExplanation formula={value(section, "formula")} method={value(section, "method")} limitations={value(section, "limitations")} /></SectionCard>; }

function WaveletTab({ section }: { section: MathematicalSection }) { const bands = value(section, "subbands"); return <SectionCard title="Multiscale wavelet analysis" eyebrow="DWT sub-bands"><MetricGrid items={[{ label: "Wavelet", value: value(section, "wavelet") }, { label: "Used level", value: value(section, "used_level") }, { label: "Max level", value: value(section, "maximum_decomposition_level") }, { label: "Noise σ", value: value(section, "estimated_noise_sigma") }, { label: "Threshold", value: value(section, "threshold") }, { label: "Detail sparsity", value: value(section, "detail_near_zero_ratio") }]} /><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Array.isArray(bands) ? bands.map((item) => { const band = item as MathematicalSection; return <div className="rounded-xl border border-line p-3" key={String(value(band, "name"))}><p className="font-mono font-semibold text-cyan">{String(value(band, "name"))}</p><p className="mt-2 text-xs text-ink-muted">Shape {JSON.stringify(value(band, "shape"))}</p><p className="mt-1 text-xs text-ink-muted">Energy {String(value(band, "energy"))}</p><Heatmap values={numberMatrix(value(band, "preview"))} label="coefficient preview" /></div>; }) : null}</div><FormulaExplanation formula={value(section, "formula")} method={value(section, "interpretation")} limitations={value(section, "limitations")} /></SectionCard>; }

function SvdTab({ section }: { section: MathematicalSection }) { return <SectionCard title="Linear algebra and singular values" eyebrow="Low-rank structure"><MetricGrid items={[{ label: "Numerical rank", value: value(section, "numerical_rank") }, { label: "Effective rank", value: value(section, "effective_rank") }, { label: "Condition number", value: value(section, "condition_number") }, { label: "90/95/99% ranks", value: JSON.stringify(value(section, "ranks_for_energy_percent")) }]} /><div className="mt-5 grid gap-4 lg:grid-cols-2"><LineChart values={numberArray(value(section, "singular_values"))} label="Singular-value spectrum" /><LineChart values={numberArray(value(section, "cumulative_energy"))} label="Cumulative Frobenius energy" color="#7C3AED" /></div><FormulaExplanation formula={value(section, "formula")} method={value(section, "interpretation")} limitations={value(section, "limitations")} /></SectionCard>; }

function TextureTab({ section }: { section: MathematicalSection }) { return <SectionCard title="Texture analysis" eyebrow="Spatial gray-level relationships"><MetricGrid items={[{ label: "Distance", value: value(section, "distance") }, { label: "Angles", value: JSON.stringify(value(section, "angles_degrees")) }, { label: "Texture entropy", value: value(section, "texture_entropy") }, { label: "Uniformity", value: value(section, "texture_uniformity") }]} /><div className="mt-5 grid gap-5 lg:grid-cols-2"><KeyValueTable values={value(section, "average_features")} /><KeyValueTable values={value(section, "directional_features")} /></div><FormulaExplanation formula={value(section, "formula")} method={value(section, "method")} limitations={value(section, "limitations")} /></SectionCard>; }

function NoiseTab({ section }: { section: MathematicalSection }) { return <SectionCard title="Noise analysis" eyebrow="Residual and heuristic indicators"><MetricGrid items={[{ label: "Estimated σ", value: value(section, "estimated_noise_standard_deviation") }, { label: "Wavelet σ", value: value(section, "wavelet_noise_sigma") }, { label: "Impulse ratio", value: value(section, "impulse_noise_ratio") }, { label: "SNR", value: value(section, "signal_to_noise_db"), unit: "dB" }, { label: "Periodic score", value: value(section, "periodic_noise_score") }, { label: "Confidence", value: value(section, "confidence") }]} /><div className="mt-5 grid gap-4 lg:grid-cols-2"><LineChart values={numberArray(value(section, "residual_histogram"))} label="Residual histogram" color="#DC2626" /><Heatmap values={numberMatrix(value(section, "residual_preview"))} label="Noise residual preview" /></div><FormulaExplanation method={value(section, "method")} interpretation={value(section, "gaussian_likeness")} limitations={value(section, "limitations")} /></SectionCard>; }

function LocalTab({ section }: { section: MathematicalSection }) { const maps = value(section, "maps"); return <SectionCard title="Local mathematical maps" eyebrow="Spatially varying metrics"><p className="text-sm leading-6 text-ink-muted">The image is divided into a {String(value(section, "grid_size"))}×{String(value(section, "grid_size"))} grid. Hover a heatmap cell to inspect row and column coordinates and the exact value.</p><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{maps && typeof maps === "object" && !Array.isArray(maps) ? Object.entries(maps).map(([name, item]) => <Heatmap key={name} values={numberMatrix(item)} label={name.replaceAll("_", " ")} />) : null}</div><FormulaExplanation method={value(section, "method")} limitations={value(section, "limitations")} /></SectionCard>; }

function CompressionTab({ section }: { section: MathematicalSection }) { return <SectionCard title="Compression potential" eyebrow="Normalized transform indicators"><MetricGrid items={[{ label: "Score", value: value(section, "score") }, { label: "Classification", value: value(section, "classification") }, { label: "DCT suitability", value: value(section, "dct_suitability") }, { label: "Wavelet suitability", value: value(section, "wavelet_suitability") }, { label: "SVD suitability", value: value(section, "svd_suitability") }]} /><div className="mt-5"><KeyValueTable values={value(section, "normalized_components")} /><ul className="mt-4 list-disc space-y-2 pl-5 text-sm leading-6 text-ink-muted">{Array.isArray(value(section, "reasons")) ? (value(section, "reasons") as unknown[]).map((reason) => <li key={String(reason)}>{String(reason)}</li>) : null}</ul></div><FormulaExplanation formula={value(section, "formula")} limitations={value(section, "limitations")} /></SectionCard>; }

function ReportTab({ analysis, section }: { analysis: MathematicalAnalysisResponse; section: MathematicalSection }) { return <SectionCard title="Mathematical analysis report" eyebrow="Structured conclusion"><p className="text-lg font-semibold text-ink">{String(value(section, "title"))}</p><div className="mt-5 grid gap-5 lg:grid-cols-2"><div><h3 className="font-semibold text-ink">Main findings</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-ink-muted">{Array.isArray(value(section, "main_findings")) ? (value(section, "main_findings") as unknown[]).map((item) => <li key={String(item)}>{String(item)}</li>) : null}</ul></div><div><h3 className="font-semibold text-ink">Careful diagnosis</h3><p className="mt-3 text-sm leading-6 text-ink-muted">{String(value(section, "careful_diagnosis"))}</p><h3 className="mt-5 font-semibold text-ink">Recommended next operation</h3><p className="mt-3 text-sm leading-6 text-ink-muted">{String(value(section, "recommended_next_operation"))}</p></div></div><div className="mt-5"><h3 className="font-semibold text-ink">Limitations</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-ink-muted">{Array.isArray(value(section, "limitations")) ? (value(section, "limitations") as unknown[]).map((item) => <li key={String(item)}>{String(item)}</li>) : null}</ul></div><div className="mt-5 flex flex-wrap gap-3"><a className="primary-button" href={mathematicalAnalysisExportUrl(analysis.id, "json")} download><Download size={16} />Download JSON</a><a className="secondary-button" href={mathematicalAnalysisExportUrl(analysis.id, "csv")} download><Download size={16} />Download CSV</a></div></SectionCard>; }
